# Generated by Django 3.0.3 on 2020-02-29 21:03

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cropperjs.models.CropperImageField(default='sample.png', upload_to='avatars/'),
        ),
    ]
